# Generated by Django 5.0.7 on 2024-09-16 22:32

import django.db.models.deletion
import prospect.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', prospect.models.UpperCaseConverter(default=None, max_length=60, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(default=None, max_length=40)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('title', models.CharField(default=None, max_length=60, null=True)),
                ('industry', models.CharField(default=None, max_length=60)),
                ('country', models.CharField(default=None, max_length=60)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company'],
            },
        ),
    ]
