# Generated by Django 5.0.7 on 2024-09-15 15:10

import prospect.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='company',
            field=prospect.models.LowerCaseConverter(default=None, max_length=60, unique=True),
        ),
    ]
