# Generated by Django 5.0.7 on 2024-09-15 15:23

import product.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=product.models.LowerCaseConverter(default=None, max_length=60, unique=True),
        ),
    ]
