# Generated by Django 5.0.7 on 2024-09-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('Won', 'Won'), ('Lost', 'Lost'), ('In Progress', 'In Progress')], default='In progress', max_length=11),
        ),
    ]
