# Generated by Django 5.0.7 on 2024-09-15 15:23

import opportunity.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_alter_opportunity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=opportunity.models.LowerCaseConverter(default=None, max_length=60, unique=True),
        ),
    ]
